// **NOTE**: this file is generated by `dhall-render`.
// You should NOT edit it manually, your changes will be lost.

ThisBuild / scalaVersion := "2.13.6"
ThisBuild / homepage := Some(url(s"https://github.com/timbertson/auditspec"))
ThisBuild / scmInfo := Some(
  ScmInfo(
    url("https://github.com/timbertson/capsul"),
    s"scm:git@github.com:timbertson/auditspec.git"
  )
)
ThisBuild / version := IO.read(new File("VERSION")).trim()

sonatypeProfileName := "net.gfxmonk"

credentials += Credentials(
  "Sonatype Nexus Repository Manager",
  "oss.sonatype.org",
  "timbertson",
  sys.env.getOrElse("SONATYPE_PASSWORD", "******"))

ThisBuild / licenses := Seq("MIT" -> url("http://www.opensource.org/licenses/mit-license.php"))

ThisBuild / developers := List(
  Developer(
    id    = "gfxmonk",
    name  = "Tim Cuthbertson",
    email = "tim@gfxmonk.net",
    url   = url("http://gfxmonk.net")
  )
)

